### ISSUE TITLE
Hard to find this site.  Copy github link to main Editorial Policy page?

### ISSUE THREAD

**Issue by briankrznarich** [JMdictProject/JMdictIssues#106]
Unless we're trying to keep github a secret except for more motivated users, in which case we're fine(this is not a sarcastic remark).

Google does not know where this site is. Neither "jmdictdb" nor "jmdict" + github return this site.   I didn't have a bookmark on a new PC, and I had to dig around to find this.  

Conscientious submitters will read the editorial page(which is linked prominently from the editing interface), but may not click through to the "Main Page" to discover there is a github link.  I know I didn't know about the github site until it was explicitly pointed out to me in an entry edit.

If we want people to know this is here, maybe we could add a blurb to the Editorial Policy page explaining that this place exists and what it is for.

**Comment by JMdictProject** [comment]
There is a link to this forum at https://www.edrdg.org/wiki/index.php/Main_Page#Documentation_and_Links It's been there since the forum was set up. I have repeated that link at the foot of the https://www.edrdg.org/wiki/index.php/Editorial_policy#Other_Issues/Policies section of the Wiki.
I'll close this now.

**Comment by JMdictProject** [comment]
Sorry; pasted the wrong URL.
