### ISSUE TITLE
Add priority form/reading tag

### ISSUE THREAD

**Issue by devorair790** [JMdictProject/JMdictIssues#109]
See this entry: https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2859272.1
"捲り返す" has 12% of the total cases so not rK, but "めくり返す" is still vastly more common. There should be a tag to denote this. It might apply to readings as well.

**Comment by stephenmk** [comment]
It's a relatively rare word in general, but the share of 捲 forms is closer to 25% in the Google corpus.

The forms are already ordered by frequency. "めくり返す" is the leading form because it's the most frequent. This is how the forms are ordered in most entries. (Long expression entries with many different combinations of kanji forms are a notable exception in which other considerations may apply).

You can find more info in the editorial policy: https://www.edrdg.org/wiki/index.php/Editorial_policy#Kanji/Special-Character_Forms
```
Google N-gram Corpus Counts
╭─ーーーーーー─┬─────┬───────╮
│ めくり返す　 │ 271 │ 66.6% │
│ 捲り返す　　 │ 112 │ 27.5% │
│ めくりかえす │  24 │  5.9% │
├─ーーーーーー─┼─────┼───────┤
│ めくり返し　 │ 685 │ 67.6% │
│ 捲り返し　　 │ 241 │ 23.8% │
│ めくりかえし │  88 │  8.7% │
╰─ーーーーーー─┴─────┴───────╯
```

**Comment by devorair790** [comment]
I still think it'd be helpful to have a "preferred form" tag to make it clear. Forms are ordered by frequency, yes, but sometimes the difference is miniscule and it makes no difference. In other cases there is a more noticeable gap, not enough to maybe add rK to the other forms but worth enough to add some sort of tag in my opinion. Also, as far as I know readings aren't necessarily ordered by frequency, right?

**Comment by JMdictProject** [comment]
I don't think we need an extra tag for the kanji forms. Apart from the [oK] and [iK} ones, which indicate 旧漢字 and incorrect kanji, we currently have:
- [sK], which indicates we consider the form to be suitable only as a search key, due to it being uncommon, incorrect, or both;
- [rK], which typically indicates that although it is uncommon enough to rate an [sK] tag, it occurs in references and hence should stay visible.

Frankly, I think these tags are enough.

**Comment by JMdictProject** [comment]
This matter is also being discussed in issue #114. I don't think we need both, so I'll close this now.
