### ISSUE TITLE
definition of auxiliary verbs

### ISSUE THREAD

**Issue by dine2014** [JMdictProject/JMdictIssues#12]
The [aux-v] tag is currently used for both:
- auxiliary verbs in traditional Japanese grammar, such as ます, よう, and た, which are regarded as suffixes in western grammars
- auxiliary verbs in western grammars, such as みる, あげる, and しまう, which is called 補助動詞 ("subsidiary verbs") in traditional Japanese grammar

The problem is, if the tag is intended to include auxiliary verbs in traditional Japanese grammar, then it should also be used for ない, たい, らしい, みたい as well as だ, です, etc., and then the [aux-adj] and [cop] tags serve no purpose. If the tag is only used for auxiliary verbs in western grammars, then which tag should be used for ます, よう, た, etc. - [aux] or [suf]?

Other tags like [aux-adj] have similar problems.

I think we should clarify our grammatical terminology, to achieve consistent PoS-tagging of such function words.

**Comment by wareya** [comment]
"Auxiliary verb" as it means to me in plain old English has a meaning that encompasses both 補助動詞 and 助動詞; I don't see an issue with using the single tag for both, as they're not truly disparate categories.

> which are regarded as suffixes in western grammars

This is by no means universal, especially for things that attach to the 連用形.

>and [cop] tags serve no purpose

The copula tag will never *not* serve a purpose.

So, this isn't just a "Japan vs the west" thing, different cultures have multiple different persuasions within themselves as well (for example, the grammar taught in schools is different from the grammar used by linguists), and I believe that there's no special reason to pick a random specific persuasion and stick to it as long as you end up with something that's coherent and isn't deceptive.

**Comment by jimmubreen** [comment]
I agree the use of "aux-v" could do with clarification. I'd certainly like to stick to a single tag for use all verb situations, and I wouldn't want to have it apply to らしい, etc. I need to think a bit about ます, よう, た, etc.

**Comment by dine2014** [comment]
@wareya 補助動詞 allow insertion of は, も, さえ, etc. while 助動詞 do not. They are separate categories like English "have" and "-ed".

**Comment by wareya** [comment]
I am not opposed to revisiting auxiliary verb tagging, but coming at it from the narrow perspective of trying to replicate some particular system (without providing a specific fully-defined system to move to) is shortsighted. These things generally tend to get worked out based on utility, at least in dictionaries.

Yes, I know how they differ. But "auxiliary verb" does not literally mean 補助動詞 and also does not literally mean 助動詞. It doesn't have to draw lines at the same points.

Or should we also split 助動詞 into the ones that affect tense, the ones that affect mode, and the ones that do other things? What about the ones that might be artifacts of analysis and might very well be fullblown 活用形 "under the hood" like the volitional よう・おう? What about the other よう and べき and such, which function very closely to nouns in 口語? What about when 補助動詞 can attach to either the 連用形 or the "te form", and can take intrusive は・も insertion in the latter case but not the former? (In other words, do we split 補助動詞 up the way the wikipedia page on them does?) Which ones of these are "auxiliary verbs" or "supplementary verbs"? Should we even use the terms or should we go even more specific like (just making stuff up here) "compounding subsidiary verbs" and "non-compounding subsidiary verbs"?

There's no objectively correct system of categorization to follow one-to-one, and existing practice is complicated and diverse, not universal. Linguistics is full of different systems and persuasions, not all of which are fully complete, and while the grammar taught in schools may be fairly complete and consistent, it's by no means more authoritative than what goes on in linguistics. Just pointing at "traditional Japanese grammar" doesn't narrow down exactly what system you're trying to refer to, and it turns out when you open up and compare the textbooks or papers that there's not much unity in "western grammars" on Japanese either, or at the very least the consistency that they do have starts to break down when you get into things like this.

If you want to open this box, I feel like you should come forward with a specific system and explain the rationale behind it rather than just pointing out something that you find to be unclear because it doesn't align with what you've seen elsewhere. It's typically the case that there's already been some kind of thought put into what groups get combined together or not in tagging, at least now that jmdict is as mature as it is today (I'm sure if you go back far enough there's going to be a lot of obvious problems).

But hey, I just kind of saw this thread show up in my email, I'm nobody special, and I'm not that well educated either!

Tangentially, comparing 助動詞 to "-ed" is very excessive. 助動詞 are not inflections as such and do not belong to the word they attach to like English verb inflections do. The proper analogue for "-ed" are the 活用形 (which is indeed literally the Japanese word typically used to describe conjugations in non-Japanese languages).

**Comment by dine2014** [comment]
Sorry, I wasn't wrong. Some western grammars, such as Samuel E Martin's _A Reference Grammar of Japanese_ uses the single label "auxiliary" for (V-i-)masu, (V-i-)hazimeru and (V-te) miru, so there's no problem with our current practice. Closing.
