### ISSUE TITLE
circa - ca. or c.?

### ISSUE THREAD

**Issue by Marcusjmdict** [JMdictProject/JMdictIssues#133]
We're using both across entries, we should probably decide which we prefer.

**Comment by JMdictProject** [comment]
I found one "circa" and eight "ca.". I couldn't find any use of "c.". I think we should use "ca." 

(I'm not a fan of having a period after abbreviations that are not truncations, so I prefer "Dr" to 'Dr.", "Mr" to Mr.", but "Rev." is OK. In this case I can live with "ca." because just "ca" can have other uses.)

PS: I changed the circa to ca.

**Comment by Marcusjmdict** [comment]
7 "c." here:
https://www.edrdg.org/jmwsgi/srchres.py?svc=jmdict&s1=1&y1=3&t1=+c.&s2=1&y2=1&t2=&s3=1&y3=1&t3=&idtyp=seq&idval=&search=Search&src=1&stat=2&appr=appr&appr=unappr&nfcmp=&nfval=&snote=&snotem=0&smtr=&smtrm=0&ts0=&ts1=&refs=&refsm=0&cmts=&cmtsm=0&mt=0&grp=

**Comment by JMdictProject** [comment]
All but one were false positives. I changed one to "ca." so that we are consistent, and several others to "century".
