### ISSUE TITLE
Unused XML elements

### ISSUE THREAD

**Issue by waacton** [JMdictProject/JMdictIssues#20]
Not necessarily an issue, but while digging deeper into my usage of JMdict & JMnedict I noticed that some XML elements specified in the DTD were not used, for example the reading info `uK` ("word usually written using kanji alone") and the `g_gend` gloss attribute.

Related, but slightly different - the DTDs between JMdict & JMnedict have some overlap, but are used a little differently. For example:
- JMdict no longer has use for certain Misc elements as they have been moved to JMnedict (e.g. `given`, `surname`, `company`, `organization`)
- JMnedict suggests kanji and reading elements can have `ke_inf`, `ke_pri`, `re_restr`, `re_inf`, `re_pri` in the same way as JMdict, but in practice they aren't used

All the above elements are not _currently_ used, and I don't know enough to guess how likely they are to be used in future! But if they do happen to be obsolete, there might be an opportunity to trim down the DTDs.

**Comment by JMdictProject** [comment]
On Sun, 8 Nov 2020 at 23:59, waacton <notifications@github.com> wrote:
> Not necessarily an issue, but while digging deeper into my usage of JMdict & JMnedict I noticed a some XML elements specified in the DTD were not used, for example the reading info uK ("word usually written using kanji alone") and the g_gend gloss attribute.

I think there were a couple of "uK" entries way back, e.g. 御目出糖, but
they lost that tag. They were mostly (all?) ateji and I think we
decided to use that instead. Yes, it could be dropped, but it's
harmless.

The "g_gend" was put in when it was thought/hoped that non-English
glosses would go in and we'd need to flag the gender of nouns, etc.
Again it could be dropped, but it's not a bother keeping it there.

> Related, but slightly different - the DTDs between JMdict & JMnedict have some overlap, but are used a little differently. For example:
>
> JMdict no longer has use for certain Misc elements as they have been moved to JMnedict (e.g. given, surname, company, organization)
> JMnedict suggests kanji and reading elements can have ke_inf, ke_pri, re_restr, re_inf, re_pri in the same way as JMdict, but in practice they aren't used

In theory they can be used, which is why they were carried over from
the JMdict DTD. In practice it's not turned out to be necessary.

> All the above elements are not currently used, and I don't know enough to guess how likely they are to be used in future! But if they do happen to be obsolete, there might be an opportunity to trim down the DTDs.

I think it's more a case of them being harmless, so they may as well stay there.

Thanks

Jim

-- 
Jim Breen
Adjunct Snr Research Fellow, Japanese Studies Centre, Monash University
http://www.jimbreen.org/
http://nihongo.monash.edu/

**Comment by JMdictProject** [comment]
I think we can move this issue "closed".
