### ISSUE TITLE
Entity "ik" is declared more than once.

### ISSUE THREAD

**Issue by sebastianbrandner** [JMdictProject/JMdictIssues#21]
IntelliJ IDEA checks the DOCTYPE and finds the following error/warning:

![jmdict-error-entity-ik](https://user-images.githubusercontent.com/1633057/98485157-9803ac80-2214-11eb-9737-a3629e202a98.png)

<!ENTITY ik "word containing irregular kana usage">

<!ENTITY ik "word containing irregular kana usage">

Not a big deal and can be fixed easily.

**Comment by JMdictProject** [comment]
Yes, "<!ENTITY ik "word containing irregular kana usage">" occurs twice.

I regard this as more of a warning rather than an error. It's an
artifact of a recent change which aligns the XML entity types with the
database tables. Since "ik" is a valid tag in both the Kanji and
Reading parts of the database, the tag definition drops into the
automatically-generated DTD in both parts. It could possibly be
organized that one of these is suppressed, but it's probably not worth
the effort.

Thanks

Jim

On Mon, 9 Nov 2020 at 08:52, Brandner Sebastian
<notifications@github.com> wrote:
>
> IntelliJ IDEA checks the DOCTYPE and finds the following error/warning:
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Jim Breen
Adjunct Snr Research Fellow, Japanese Studies Centre, Monash University
http://www.jimbreen.org/
http://nihongo.monash.edu/

**Comment by JMdictProject** [comment]
I think we can regard this issue as closed.
