### ISSUE TITLE
Updates to misc and field tags - July 2022

### ISSUE THREAD

**Issue by JMdictProject** [JMdictProject/JMdictIssues#68]
I'm pulling things together for a long-overdue update to the misc and field tags. As the discussions have been spread over several issues, I'm going to summarize the proposed changes in this issue and close the others.

**Misc tags**

Remove the current [rare] tag and instead use it for the entries marked [obsc]. #64 
(currently no entries are using [rare]. There are 2,286 entries tagged [obsc] and with a table change these will become [rare].)

Add [ship] (ship name) for use in JMnedict. #54 

Add [euph] (euphemism). #53 

**Field tags**

Add [manga] #41  Once this is in place the 29 entries with the [m-sl] can be retagged and the [m-sl] misc tag retired.

Add [dent] (dentistry) #54 

Change [hanaf] to [cards] to make it more general. #54

Change the description of [pharm] to pharmacology.

Add [histj] (event in Japanese history) [mining] [kabuki] [noh] [politics] [stockm] (stock market) [ski] (skiing) [rommyth] (Roman mythology) [psyanal] (psychoanalysis) [film] [TV] - most of these are from #31  

Suggestions for further changes or additions should be made to this issue.

**Comment by robinjmdict** [comment]
I suggested the "Japanese history" tag some time ago but we've already tagged so many Japanese historical terms as "hist" that it's probably not worth introducing a new tag at this point. We seem to be doing fine without it.

I'm not sure about changing [hanaf] to [cards]. Looking through our hanaf-tagged entries, I see that most of them don't apply to Western card games. How much overlap is there with other types of Japanese playing cards? Could we have a separate "cards" tag to be used alongside "hanaf"?

This is a minor thing but I suggest making the description of [euph] "euphemistic" (and also changing "archaism" to "archaic" and "colloquialism" to "colloquial") so that it's consistent with the other tag descriptions (dated, derogatory, jocular, etc.)

**Comment by Marcusjmdict** [comment]
Re:hanafuda, the majority of the words tagged with it are specifically about hanafuda (or more specifically about the game hachi-hachi) - I've avoided tagging playing card terms that aren't exclusively hanafuda-related with that tag. But several of them do stem from mekuri karuta and other games originally (and sometimes still) played with other decks such as kabufuda.  
The problem with restricting the tag to [karuta] then is that the mekuri karuta (though not produced commercially since maybe the 1990s) itself is derived from European 4-suited decks and could essentially be called a Latin-suited deck, the difference is really only cosmetic. The most popular of the games that can be played with these types of decks is oicho kabu, which as I mentioned in the original post are most commonly played with a regular Western deck. 

Entries tagged with [hanafuda] that also apply to other karuta games (out of 110-ish)
ガンを付ける, カス札, 三光, 出来役, 大役, 四光 (possibly), 尾季 (probably), 差し, 役札, 役逃げ (poss), 滓, 胴, 胴中, 胴二, 親権 (poss), テンショ, 起こし (poss), 鬼札, がん, スベタ, びけ

Entries tagged with [hanafuda]that also apply to Western card games
めくり札　

Entries that aren't tagged with [hanafuda] but could be tagged [karuta] or [cards]:
青二　青札 赤札 ロハイ 三枚ガルタ　かぶ おいちょかぶ 釈迦十 馬　青一 赤札 追丁 キリ　親

But then again I've heard knowledgeable people argue that mahjong is a card game, and we do have a separate tag for that..

**Comment by JMdictProject** [comment]
Summarizing proposed variations to my original collection:
- don't proceed with [histj]
- retain [hanaf] and add another category for other card games. Suggestions are [cards] and [karuta]. I'd go for [cards]. Some entries could be both [hanaf] and [cards].
- tweak the descriptions of [arch], [col] and [euph].

**Comment by JMdictProject** [comment]
I have just implemented the changes to the miscellaneous tags. In summary:
- the [obsc] entries are now tagged as [rare]. [obsc] is no longer available.
- the new [euph] tag is available
- the descriptions of the [col] and [arch] tags have been tweaked.

I'll test and install the proposed field changes in the next day or so.

**Comment by JMdictProject** [comment]
The additional field tags are now in place and available. I just sent a message about it to the general mailing list.
I also added the [ship] JMnedict name type which I overlooked yesterday.

**Comment by Marcusjmdict** [comment]
Great! The description for the [cards] tag should probably be "playing
cards" rather than just "cards".
Best,
Marcus

**Comment by robinjmdict** [comment]
I'd go with "card games". That's what Wiktionary uses.

I see that the tag has already been added to entries like ポーカー and ブラックジャック but I'm not sure it should be used for names of cards games. We don't tag サッカー, 野球, etc. as [sports].

**Comment by JMdictProject** [comment]
The description for [cards] is now "card games.".

**Comment by robinjmdict** [comment]
I think we should have a boxing field tag. 62 entries tagged as 【ボクシング】in GG5.

**Comment by JMdictProject** [comment]
アノニマスさん has suggested a tag for Chinese mythology.

**Comment by Marcusjmdict** [comment]
Should we have one for Japanese mythology as well?

**Comment by Marcusjmdict** [comment]
Can we decide on a specific scope for [politics]? There's only a handful of entries that have it and I'd like to tag some more. Should or should it not be applied to
- political parties and organizations (e.g. 日本会議)
- words like 上下両院, 国会
etc.
