### ISSUE TITLE
Verb class tags on proverbs, yes or no?

### ISSUE THREAD

**Issue by Marcusjmdict** [JMdictProject/JMdictIssues#69]
Stephen has suggested that verb class tags should be included in proverb entries like [出る杭は打たれる](https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&q=1985430.1). 

Stephen:

> Google N-gram Corpus Counts 
> ```
> ╭─ーーーーーーーーー─┬────────╮ 
> │ 出る杭は打たれる　 │ 24,938 │ 
> │ 出る杭は打たれます │    424 │ 
> │ 出る杭は打たれない │    747 │ 
> │ 出る杭は打たれた　 │    255 │ 
> │ 出る杭は打たれて　 │    638 │ 
> ╰─ーーーーーーーーー─┴────────╯
> ```
> I think we should keep the [v1] tags.

Robin:
>I don't think verb class tags are appropriate for proverbs. They're fixed expressions. They shouldn't conjugate.

Stephen:

> The inflected forms get 2,064 out of 27,002 counts (7.6%).
> 
> If you look up 「出る杭は打たれます」 with, say, jisho.org or
> yomichan, you won't find this entry. There are also, for example,
> people who read books on tablets and e-readers who use text
> scanning software to find definitions, and even if they suspect
> 「出る杭は打たれます」 might be an inflected form of an idiom,
> it's especially inconvenient for them to exit their applications
> and manually search for the de-inflected text elsewhere.

> Maybe this is a more convincing argument. The American proverb
> is "the squeaky wheel gets the grease." Nobody would bat an eye
> if I were to say "the squeaky wheel got the grease," "will get
> the grease," "didn't get the grease" (ironically), etc. If I were
> learning English, it would be really convenient if I had a way to
> tie these derivatives back to the original form of the proverb.

This was discussed previously some years ago though I can't figure out exactly where (probably in an entry). Our current unwritten policy is to not include the verb class tags.

**Comment by stephenmk** [comment]
To the extent that proverbs can be said to be fixed expressions, I think the presence of the "proverb" tag is enough to get that point across. I don't think the presence of verb tags is likely to cause confusion, and it is undeniable that people will come across inflected versions of these proverbs.

If an application designer is concerned that the presence of a verb tag may confuse users, then it would be trivial to hide the verb tags on all proverbs. I don't think we should be imposing these design decisions by force, especially at the expense of useful functionality.

**Comment by JMdictProject** [comment]
While I don't really mind either way, I think Stephen has demonstrated quite a few cases where the verb endings in proverbs are being used in inflected forms. I'm quite happy to have the inflection class included with such proverbs, etc. It's basically harmless and at the margin possibly useful.

**Comment by melink14** [comment]
Just a side vote in favor of keeping them; as a dev using the data (and a user) it usually is viewed as a bug when verb like expressions don't conjugate.

**Comment by stephenmk** [comment]
[Discussion from 2014](https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&q=2418030)

Here's an example of a proverb entry in which half of the n-gram counts are inflected forms.

[seq 2416640, なるようになる](https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&q=2416640)
```
╭─ーーーーーーーーーーー─┬─────────┬───────╮
│ なるようになる　　　　 │ 129,562 │ 54.8% │
│ なるようになります　　 │   6,926 │  2.9% │
│ なるようにならない　　 │     771 │  0.3% │
│ なるようになりません　 │      48 │  0.0% │
│ なるようになった　　　 │  23,091 │  9.8% │
│ なるようになりました　 │  22,826 │  9.6% │
│ なるようにならなかった │      25 │  0.0% │
│ なるようになって　　　 │  48,650 │ 20.6% │
│ なるようになりまして　 │     235 │  0.1% │
│ なるようにならなくて　 │      46 │  0.0% │
│ なるようになったら　　 │   1,700 │  0.7% │
│ なるようになりましたら │      90 │  0.0% │
│ なるようになれば　　　 │   2,487 │  1.1% │
│ なるようにならなければ │     125 │  0.1% │
│ なるようになれる　　　 │      53 │  0.0% │
├─ーーーーーーーーーーー─┼─────────┼───────┤
│ 成るように成る　　　　 │   2,094 │ 88.1% │
│ 成るように成ります　　 │      52 │  2.2% │
│ 成るように成った　　　 │      67 │  2.8% │
│ 成るように成って　　　 │     144 │  6.1% │
│ 成るように成れば　　　 │      21 │  0.9% │
╰─ーーーーーーーーーーー─┴─────────┴───────╯
```

Here are some more examples. You don't have to try particularly hard to find these. If a proverb ends with a verb and its base form gets more than a few thousand n-grams, then its inflections are bound to pick up some counts as well.

[seq 2416640, 君子豹変す](https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&q=2417080)
```
╭─ーーーーーー─┬─────┬───────╮
│ 君子豹変す　 │ 922 │ 86.4% │
│ 君子豹変した │  67 │  6.3% │
│ 君子豹変して │  78 │  7.3% │
╰─ーーーーーー─┴─────┴───────╯
```

[seq 2079030, 大は小を兼ねる](https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&q=2079030)
```
╭─ーーーーーーーー─┬────────┬───────╮
│ 大は小を兼ねる　 │ 26,431 │ 89.5% │
│ 大は小を兼ねます │    814 │  2.8% │
│ 大は小を兼ねない │  1,943 │  6.6% │
│ 大は小を兼ねず　 │     96 │  0.3% │
│ 大は小を兼ねた　 │     26 │  0.1% │
│ 大は小を兼ねて　 │    229 │  0.8% │
╰─ーーーーーーーー─┴────────┴───────╯
```

[seq 2418090, 寝る子は育つ](https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&q=2418090)
```
╭─ーーーーーーーーーー─┬────────┬───────╮
│ 寝る子は育つ　　　　 │ 55,646 │ 96.4% │
│ 寝る子は育ちます　　 │    723 │  1.3% │
│ 寝る子は育たない　　 │    145 │  0.3% │
│ 寝る子は育った　　　 │    410 │  0.7% │
│ 寝る子は育ちました　 │     22 │  0.0% │
│ 寝る子は育たなかった │    628 │  1.1% │
│ 寝る子は育って　　　 │    170 │  0.3% │
╰─ーーーーーーーーーー─┴────────┴───────╯
```

There are over 800 entries in JMdict with the proverb tag. I can make a list of [adj-i] and verb-ending entries to be updated in bulk if we're all in agreement.

**Comment by Marcusjmdict** [comment]
So the last time this was discussed, I was in favor of having verb tags, but I guess I was convinced by Robin (and Rene? my memory's a little fuzzy) that if you conjugate a proverb, you're not really talking about the same proverb any longer, it ends up being a reference to one. "the apple falls far from the tree" is not the same thing as "the apple does not fall far from the tree". While it might still be convenient to pick up on those rarer forms so that apps and dictionaries etc. can lead the users to the proverb being referenced, I'm not sure we really want to show those verb tags to the end user.

**Comment by stephenmk** [comment]
I have to say that the distinction between proverbs, forms of proverbs, and references to proverbs seems rather academic and of far less interest to users than actually being able to find these entries. But again, I don't think it has to be one or the other. If an application designer wants to hide verb tags from entries with the proverb tag, then doing so is very simple. On the other hand, adding inflection tags to terms which lack them is not something that we can expect anyone to do.

The situation seems to be that the verb class tags are overloaded with two functionalities (one for display and one for inflection). Short of redesigning JMDict to logically separate these two purposes, I think that adding the verb tags now offers the greatest benefit and least harm to users.

If I look up 食べない with any of the various dictionary applications based on JMdict, I'll find an entry tagged as an ichidan verb and a gloss which says "to eat." But 食べない is not an ichidan verb and it does not mean "to eat." This scenario does not present any difficulty for users because they are accustomed to how de-inflection works, and they are aware that the verb class tags and glosses only apply to the dictionary form of the word. 

I'll admit that I'm stretching this argument a bit. Unlike glosses and verb tags, miscellaneous tags are usually applicable to all inflected forms of an term. But anyone familiar with the concept of proverbs knows that they typically exist in a canonical form. The form displayed in the dictionary is obviously this canonical form. I can't imagine that the presence of a verb class tag will be interpreted by anyone as a free license to use the expression however they see fit. If they are misused in this way (by someone who is advanced enough to be able to incorporate proverbs into their speech), then such a person would ~certainly~ hopefully soon be corrected. I think that's just a normal part of language acquisition.

**Comment by JMdictProject** [comment]
This is an aside related to Stephen's comment on looking up 食べない.
In my ancient 1990s X11 dictionary client "xjdic" (from which a lot of code ended up in WWWJDIC), I tried to address this issue. A few hardy people still use xjdic, and if you look up 食べない in it you get:
"Possible inflected verb or adjective: (plain, negative, nonpast)
食べる （たべる） (v1,vt) (1) to eat, (v1,vt) (2) to live on (e.g. a salary), 
to live off, to subsist on, (P)"

I never bothered to carry that functionality into WWWJDIC but perhaps I should have. It actually seems to work.

**Comment by JMdictProject** [comment]
Having thought about this general issue some more, I think it would be best to allow inflecting information to be included with the surface forms in proverbs and similar expressions. I can see that in a number of cases it would be useful.

**Comment by stephenmk** [comment]
Here's a list of proverbs that I think we can update. For each proverb, I searched JMdict for the longest matching suffix substring. I reviewed and touched-up the results, so I think it's good to go.

https://gist.github.com/stephenmk/693e9687afbeafca9e8e302a9bedffeb

**Comment by JMdictProject** [comment]
I think this is worth doing. It covers about 1/4 of the entries with "prov" tags. If there are no contrary arguments, I can action this via bulk update next week.

**Comment by JMdictProject** [comment]
OK, that's done. I'll close this now.
